# -*- coding: utf-8 -*-
"""Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGa9JZxZZyPp_1JK2wcA4G5H8R6A5Jkj

https://drive.google.com/file/d/1Mqwh3Ecx2fOC_hKQfU4miAF2n2TfJH08/view?usp=drive_link

Recommendation System
"""

import pandas as pd
import numpy as np

# Machine Learning
from sklearn.metrics.pairwise import cosine_similarity

# Load Dataset
df = pd.read_csv("recommendation_system_dataset.csv")

# Display Dataset
print(df.head())

# Dataset Information
print(df.info())

# Create User-Movie Matrix
movie_matrix = df.pivot_table(
    index="UserID",
    columns="Movie",
    values="Rating"
).fillna(0)

print("\nUser Movie Matrix:\n")

print(movie_matrix)

# Calculate Similarity
similarity = cosine_similarity(movie_matrix)

# Convert Similarity into DataFrame
similarity_df = pd.DataFrame(
    similarity,
    index=movie_matrix.index,
    columns=movie_matrix.index
)

print("\nSimilarity Matrix:\n")

print(similarity_df)

# Recommendation Function
def recommend_movies(user):

    similar_users = similarity_df[user].sort_values(
        ascending=False
    )

    similar_users = similar_users[1:6]

    print("\nTop Similar Users:\n")

    print(similar_users)

    recommended_movies = {}

    for similar_user in similar_users.index:

        user_movies = df[
            (df["UserID"] == similar_user)
            & (df["Rating"] >= 4)
        ]["Movie"]

        for movie in user_movies:

            if movie in recommended_movies:
                recommended_movies[movie] += 1
            else:
                recommended_movies[movie] = 1

    recommended_movies = sorted(
        recommended_movies.items(),
        key=lambda x: x[1],
        reverse=True
    )

    print("\nRecommended Movies:\n")

    for movie, score in recommended_movies[:5]:
        print(movie)

# Example Recommendation
recommend_movies("User_10")