# -*- coding: utf-8 -*-
"""Resume Screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diG17WOThjiJvdA0Pkeb0g1grnZo7FX1

https://drive.google.com/file/d/19youdZJqkjuZCSWbbnFEW-RyTRxxe7fn/view?usp=drive_link

Resume Screening
"""

import pandas as pd
import numpy as np

# NLP Libraries
from sklearn.feature_extraction.text import TfidfVectorizer

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Model
from sklearn.naive_bayes import MultinomialNB

# Evaluation
from sklearn.metrics import accuracy_score, classification_report

# Load Dataset
df = pd.read_csv("resume_screening_dataset.csv")

# Display Dataset
print(df.head())

# Check Missing Values
print(df.isnull().sum())

# Encode Categorical Columns
le = LabelEncoder()

df["Education"] = le.fit_transform(df["Education"])

df["JobRole"] = le.fit_transform(df["JobRole"])

# Features
text_features = df["Skills"]

# Convert Skills Text into Numbers
vectorizer = TfidfVectorizer()

skills_vector = vectorizer.fit_transform(text_features)

# Numerical Features
numerical_features = df[["Experience", "Education", "JobRole"]].values

# Combine Features
from scipy.sparse import hstack

X = hstack((skills_vector, numerical_features))

# Target
y = df["Selected"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = MultinomialNB()

model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Classification Report
print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

# Predict New Resume
new_resume = ["Python Machine Learning SQL Power BI"]

# Convert Text
new_resume_vector = vectorizer.transform(new_resume)

# Additional Features
new_features = np.array([[3, 1, 2]])

# Combine Features
from scipy.sparse import csr_matrix

combined_features = hstack((
    new_resume_vector,
    csr_matrix(new_features)
))

# Predict
prediction = model.predict(combined_features)

if prediction[0] == 1:
    print("\nResume Selected")
else:
    print("\nResume Rejected")