# -*- coding: utf-8 -*-
"""Sentimental Detection .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yZ3xOgRzFYSaPNKYz04kWywxvyTzZZfZ

https://drive.google.com/file/d/1rhR6RjW1m6IPfeuNUvgIdSYN9ipfOEA2/view?usp=drive_link

Sentimental Detection
"""

import pandas as pd
import numpy as np

# NLP Libraries
import nltk
import re

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Evaluation
from sklearn.metrics import accuracy_score, classification_report

# Download Stopwords
nltk.download('stopwords')

# Load Dataset
df = pd.read_csv("sentiment_dataset.csv")

# Display Dataset
print(df.head())

# Check Missing Values
print(df.isnull().sum())

# Initialize Stemmer
ps = PorterStemmer()

# Text Cleaning Function
def clean_text(text):

    # Remove Special Characters
    text = re.sub('[^a-zA-Z]', ' ', text)

    # Convert to Lowercase
    text = text.lower()

    # Split Words
    text = text.split()

    # Remove Stopwords and Apply Stemming
    text = [
        ps.stem(word)
        for word in text
        if not word in stopwords.words('english')
    ]

    # Join Words
    text = ' '.join(text)

    return text

# Apply Cleaning
df["Cleaned_Review"] = df["Review"].apply(clean_text)

# Features and Target
X = df["Cleaned_Review"]

y = df["Sentiment"]

# Convert Text into Numbers using TF-IDF
vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(X)

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = MultinomialNB()

model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy:", accuracy)

# Classification Report
print("\nClassification Report:\n")

print(classification_report(y_test, y_pred))

# Predict Custom Review
review = ["This product is absolutely amazing"]

# Clean Review
cleaned_review = [clean_text(review[0])]

# Convert into Vector
vector_review = vectorizer.transform(cleaned_review)

# Predict Sentiment
prediction = model.predict(vector_review)

print("\nPredicted Sentiment:", prediction[0])